---
title: "Import"
author: "EJ Arce"
date: "4/2/2017"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE)
library(foreign)
library(dplyr)
library(tidyverse)
library(readxl)
```

### Import

```{r, warning=FALSE, message=FALSE}
LegResults6814 <- read.dta("032_StateLegForecast_CAcopy/SLERs1967to2015_20160912b_CA.dta")

LegResults16 <- read_excel("032_StateLegForecast_CAcopy/001_CA2016GenOfficecopy.xls")

threeoffices9008 <- read_excel("032_StateLegForecast_CAcopy/aaa_All_States_1968_2010_2013_03_22_CAonly.xlsx")

threeoffices6688 <- read_excel("032_StateLegForecast_CAcopy/033_CA_1966to1988_20160715_FromNicole.xlsx")
```

### Wrangle and Tidy

```{r, warning=FALSE, message=FALSE}
# Selecting and renaming variables of interest; Filtering the dataset to only include democratic and republican candidates.
LegResults6814 <- LegResults6814 %>%
  select(v05, v07, v09z, v19, v21, v22, v23) %>%
  rename(year = v05,
         chamber = v07,
         District = v09z,
         candidate = v19,
         party = v21,
         incumbency = v22,
         votes = v23) %>%
  filter(party == c(100, 200))
LegResults6814$chamber <- ifelse(LegResults6814$chamber == 8, "SEN", "HS")
LegResults6814$party <- ifelse(LegResults6814$party == 100, "Dem", "Repub")

LegResults16 <- LegResults16 %>%
  select(v05, v07, v09, name_original, partyoriginal, v23) %>%
  rename(year = v05,
         chamber = v07,
         District = v09,
         candidate = name_original,
         party = partyoriginal,
         votes = v23) %>%
  filter(party == c("Democratic", "Republican"))

LegResults16$chamber <- ifelse(LegResults16$chamber == 8, "SEN", "HS")
LegResults16$party <- ifelse(LegResults16$party == "Democratic", "Dem", "Repub")

# Selecting variables of interest for the database of results for 3 offices, recoding v07 to return SEN or HS, and renaming v07 as "chamber" for 9008

threeoffices9008$v07 <- ifelse(threeoffices9008$v07 == 8, "SEN", "HS")

threeoffices9008 <- threeoffices9008 %>%
  select(2:4, 6:9, 11, 12, 15, 16) %>%
  rename(year = v05, District = v09, chamber = v07)

threeoffices6688 <- threeoffices6688 %>%
  select(1, 3, 4, (17:25)) %>%
  rename(District = dist) %>%
  filter(Dummy1 == 1)
  
threeoffices6688$chamber <- ifelse(threeoffices6688$chamber == "S", "SEN", "HS")
```

### Join

```{r, warning=FALSE, message=FALSE}
# Joining threeoffices6688 and threeoffices9008 into threeoffices
threeoffices6608 <- full_join(threeoffices6688, threeoffices9008, key = "year")

# Create threeoffices1016 and recode chamber entries
threeoffices1016 <- read_excel("032_StateLegForecast_CAcopy/California_2010_2016.xlsx")
threeoffices1016$chamber <- ifelse(threeoffices1016$chamber == "S", "SEN", "HS")

# Join threeoffices6608 and threeoffices1016
threeoffices6616 <- full_join(threeoffices6608, threeoffices1016, key = "year")
```

